name: scikit-learn-tutorial

channels:
  - conda-forge

dependencies:
  - scikit-learn
  - pandas >= 1
  - conda-forge::pandas-profiling >= 2.5
  - matplotlib-base
  - seaborn
  - jupyterlab
  - notebook
  - jupytext
  - jupyter-offlinenotebook
  - jupyterlab-jupytext
