#!/bin/sh
jupyter lab build --dev-build=False  --minimize=False


echo 'export OMP_NUM_THREADS=2' >> ~/.bashrc
echo 'export OPENBLAS_NUM_THREADS=2' >> ~/.bashrc
echo 'export MKL_NUM_THREADS=2' >> ~/.bashrc
